version: '3'

services:
  web:
    build: .
    #volumes:
    #  - .:/code
    #command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - MYSQL_ROOT_PASSWORD=B00704995
      - MYSQL_USER=root
      - MYSQL_DATABASE=Company
  redis:
    image: "web"
