# Generated by Django 2.1.5 on 2019-02-07 23:05

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=15)),
            ],
        ),
    ]
