# Generated by Django 2.1.5 on 2019-02-08 02:16

from django.db import migrations, models
import pymysql

pymysql.install_as_MySQLdb()

class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEPARTMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPARTMENT_NUM', models.IntegerField()),
                ('DEPARTMENT_NAME', models.CharField(max_length=15)),
                ('DEPARTMENT_PHONE', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EMPLOYEE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPLOYEE_NUM', models.CharField(max_length=15)),
                ('EMPLOYEE_FNAME', models.CharField(max_length=15)),
                ('EMPLOYEE_LNAME', models.CharField(max_length=15)),
                ('DEPARTMENT_NAME', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
